---
- name: "Restart composed service homepage"
  become: true
  ansible.builtin.command:
    cmd: "nerdctl compose restart homepage"
    chdir: "/home/{{ users.0.username }}/compose/"

# - name: "Restart composed service TODO"
#   become: true
#   ansible.builtin.command:
#     cmd: "nerdctl compose restart TODO"
#     chdir: "/home/{{ users.0.username }}/compose/"

- name: "Restart composed Caddy"
  become: true
  ansible.builtin.command:
    cmd: "nerdctl compose restart caddy"
    chdir: "/home/{{ users.0.username }}/compose/"

- name: Restart nsd
  ansible.builtin.service:
    name: nsd
    state: restarted
