# vi: ft=yaml
---
- name: Classify hosts depending on their OS distribution
  ansible.builtin.group_by:
    key: os_{{ ansible_facts['distribution'] }}
  changed_when: false

- name: Show facts available on the system
  ansible.builtin.debug:
    var: ansible_facts
  when: debug | default(false)

- name: Manage local users
  ansible.builtin.include_tasks:
    file: local-users.yml
  when:
    - ansible_facts['system'] == "Linux"

# Package management in this file uses/supports:
#   - ansible_facts['architecture'] (linux => {x86_64,aarch64}, darwin => {arm64})
#   - ansible_facts['distribution'] ( {Debian,Ubuntu,MacOSX})
#   - ansible_facts['distribution_major_version']: { Debian => [12,13], Ubuntu => [22,24], MacOSX => [14,15] }

- name: Install common packages
  become: "{{ (ansible_facts['system'] == 'Linux')|ternary(true,false) }}"
  ansible.builtin.package:
    name: "{{ common_packages.common }}"
    state: latest
  # Remove this condition once we can install on all inventory distros?
  # when: ansible_facts['system'] == 'Linux'

- name: Uninstall common undesirable packages
  become: "{{ (ansible_facts['system'] == 'Linux')|ternary(true,false) }}"
  ansible.builtin.package:
    name: "{{ common_undesirable_packages[ansible_facts['distribution']]|default(omit) }}"
    state: absent
    purge: true
  # Remove this condition once we can install on all inventory distros?
  when: ansible_facts['system'] == 'Linux' and ansible_facts['hostname'] != 'x1c'

- name: Install distro packages
  become: "{{ (ansible_facts['system'] == 'Linux')|ternary(true,false) }}"
  ansible.builtin.package:
    name: "{{ common_packages[ansible_facts['distribution'] + '_' + ansible_facts['distribution_major_version']] | default(omit) }}"
    state: latest
  when: ansible_facts['system'] == "Linux"

- name: Upgrade (linux) packages
  become: true
  ansible.builtin.package:
    update_cache: true
    upgrade: true
  when: ansible_facts['system'] == "Linux"
  register: upgrade_packages

- name: Show the upgraded packages
  ansible.builtin.debug:
    msg: "{{ upgrade_packages.results[0].stdout_lines }}"
  when:
    - upgrade_packages.changed
    - upgrade_packages.results| default([])|length > 0

# TODO: firmware upgrades?
# fwupdmgr -y refresh && fwupdmgr -y upgrade

- name: Check whether Homebrew is installed
  stat:
    path: "{{ common_brew_basepath[ansible_facts['system']] + '/bin/brew' }}"
  register: homebrew_check
  # when:
  #   - not (ansible_facts['os_family'] == 'Debian' and ansible_facts['architecture'] == 'aarch64')

- name: Install XCode Command Line Tools
  become: true
  ansible.builtin.command:
    argv:
      - xcode-select
      - --install
  when:
    - ansible_facts['distribution'] == "MacOSX"
    - not homebrew_check.stat.exists

- name: Running misc setup for MacOS
  ansible.builtin.include_tasks:
    file: misc-darwin.yml
  when:
    - ansible_facts['distribution'] == "MacOSX"

- name: Running misc setup for RPi
  ansible.builtin.include_tasks:
    file: misc-rpi.yml
  when:
    - ansible_facts['distribution'] == "Debian" and ansible_facts['architecture'] == "aarch64"

- name: Create homebrew directory
  become: true
  ansible.builtin.file:
    path: /home/linuxbrew
    owner: root
    group: root
    state: directory
    mode: '0755'
  when:
    - not homebrew_check.stat.exists
    # - ansible_facts['system'] == "Linux" and (not ansible_facts['architecture'] == "aarch64")

- name: Create homebrew directory
  become: true
  ansible.builtin.file:
    path: /home/linuxbrew/.linuxbrew
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    state: directory
    mode: '0755'
  when:
    - not homebrew_check.stat.exists
    # - ansible_facts['system'] == "Linux" and (not ansible_facts['architecture'] == "aarch64")


# TODO: This came direct from docs.brew.sh. Replace with builtin.get_url?
- name: Download Homebrew installer
  become: false
  environment:
    NONINTERACTIVE: 1
  ansible.builtin.command:
    argv:
      - curl
      - -fsSL
      - -o
      - homebrew_installer.sh
      - "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
  when:
    - not homebrew_check.stat.exists
    # - not ansible_facts['architecture'] == "aarch64"

- name: Install Homebrew
  become: false
  environment:
    NONINTERACTIVE: 1
  ansible.builtin.command:
    argv:
      - bash
      - homebrew_installer.sh
    creates: "{{ common_brew_basepath[ansible_facts['system']] + '/bin/brew' }}"
  when:
    - not homebrew_check.stat.exists
    # - not ansible_facts['architecture'] == "aarch64"
  register: homebrew_installed

# TODO: add homebrew/bin and homebrew/sbin to PATH?

- name: Manage Homebrew taps (common)
  become: false
  environment:
    NONINTERACTIVE: 1
  ansible.builtin.homebrew_tap:
    name: "{{ common_brew_taps.common }}"
    path: "{{ common_brew_basepath[ansible_facts['system']] + '/bin' }}"
    state: present
  when: homebrew_check.stat.exists or homebrew_installed.changed

- name: Unlink uutils-coreutils formula
  # separate task because of conflict with formula: coreutils
  become: false
  environment:
    NONINTERACTIVE: 1
  ansible.builtin.homebrew:
    name: uutils-coreutils
    path: "{{ common_brew_basepath[ansible_facts['system']] + '/bin' }}"
    state: unlinked
    update_homebrew: false
  ignore_errors: true
  when:
    - homebrew_check.stat.exists

- name: Update homebrew
  become: false
  environment:
    NONINTERACTIVE: 1
  ansible.builtin.command:
    argv:
      - "{{ common_brew_basepath[ansible_facts['system']] + '/bin/brew' }}"
      - update
  when:
    - homebrew_check.stat.exists
  register: homebrew_updated

- name: Manage Homebrew formulae
  become: false
  environment:
    NONINTERACTIVE: 1
  ansible.builtin.homebrew:
    name: "{{ common_brew_formulae.common + common_brew_formulae[ansible_facts['system']] | default ([]) }}"
    path: "{{ common_brew_basepath[ansible_facts['system']] + '/bin' }}"
    state: latest
    upgrade_all: true
    update_homebrew: "{{ (ansible_facts['system'] == 'Linux')|ternary(not homebrew_updated.changed,false) }}"
  when:
    - homebrew_check.stat.exists or homebrew_installed.changed
  register: homebrew_formulae

- name: Show Homebrew formulae changes
  ansible.builtin.debug:
    msg: "{{ homebrew_formulae.changed_pkgs }}"
  when: homebrew_formulae.changed

- name: "Manage uutils-coreutils https://uutils.github.io"
  # separate task because of conflict with formula: coreutils
  become: false
  environment:
    NONINTERACTIVE: 1
  ansible.builtin.homebrew:
    name: uutils-coreutils
    path: "{{ common_brew_basepath[ansible_facts['system']] + '/bin' }}"
    state: latest
    update_homebrew: false
  when:
    - homebrew_check.stat.exists or homebrew_installed.changed

- name: Manage Homebrew formulae by Group
  become: false
  environment:
    NONINTERACTIVE: 1
  ansible.builtin.homebrew:
    name: "{{ common_brew_formulae[item] | default (common_brew_formulae['minimal']) }}"
    path: "{{ common_brew_basepath[ansible_facts['system']] + '/bin' }}"
    state: latest
    update_homebrew: false
  with_items:
    - workstation
    - server
  when:
    - homebrew_check.stat.exists or homebrew_installed.changed
    - "item in group_names"

- name: Re-link uutils-coreutils formula
  # separate task because of conflict with formula: coreutils
  become: false
  environment:
    NONINTERACTIVE: 1
  ansible.builtin.command:
    argv:
      - "{{ common_brew_basepath[ansible_facts['system']] + '/bin/brew' }}"
      - link
      - --overwrite
      - uutils-coreutils
  when:
    - homebrew_check.stat.exists or homebrew_installed.changed

- name: Query for requested Homebrew formulae
  become: false
  environment:
    NONINTERACTIVE: 1
  ansible.builtin.command:
    argv:
      - "{{ common_brew_basepath[ansible_facts['system']] + '/bin/brew' }}"
      - leaves
      - -r
  when:
    - homebrew_check.stat.exists or homebrew_installed.changed
  register: homebrew_leaves

- name: Show requested Homebrew formulae
  ansible.builtin.debug:
    msg: "{{ homebrew_leaves.stdout_lines }}"
  when:
    - homebrew_check.stat.exists or homebrew_installed.changed

- name: Dump Homebrew formulae to Brewfile
  become: false
  environment:
    NONINTERACTIVE: 1
  ansible.builtin.command:
    argv:
      - "{{ common_brew_basepath[ansible_facts['system']] + '/bin/brew' }}"
      - bundle
      - dump
      - --force
      - --describe
      - --file=Brewfile
  # --force, overwrites an existing Brewfile
  # --describe, adds a description comment
  changed_when: false
  when:
    - homebrew_check.stat.exists
    - homebrew_formulae.changed

# - name: debug a/some var(s)
#   tags: debug
#   ansible.builtin.debug:
#     var: groups

- name: Check whether snapd is installed
  tags: debug
  stat:
    path: /usr/bin/snap
  register: snapd_check

- name: Disable snapd
  ansible.builtin.service:
    name: snapd
    state: stopped
    enabled: false
    # daemon_reload: true
  ignore_errors: true
  when:
    - inventory_hostname in groups['server']
    - ansible_facts['distribution'] == "Ubuntu"
    - snapd_check.stat.exists

- name: Include containerd.yml
  ansible.builtin.include_tasks:
    file: containerd.yml
    apply:
      tags:
        - containerd
  when:
    - ansible_facts['distribution'] == "Debian"
